myvideoapp/config/routes.rb
Rails.application.routes.draw do
  root 'videos#index'
  resources :videos
end

myvideoapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myvideoapp/app/models/usage.rb
class Usage < ApplicationRecord
  validates :user_id, presence: true
  validates :video_id, presence: true
  belongs_to :video
  belongs_to :user
  validates_associated :video
  validates_associated :user
end

myvideoapp/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :usage
  has_many :videos, through: :usage
end

myvideoapp/app/models/video.rb
class Video < ApplicationRecord
  validates :name, presence: true
  has_many :usages
  has_many :users, through: :usages
end

myvideoapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

myvideoapp/app/controllers/usage_controller.rb
class UsagesController < ApplicationController
  
end

myvideoapp/app/controllers/user_controller.rb
class UsersController < ApplicationController
end

myvideoapp/app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
    # give chart thing its data
  end
end

myvideoapp/app/helpers/application_helper.rb
module ApplicationHelper
end

myvideoapp/app/helpers/usage_helper.rb
module UsageHelper
end

myvideoapp/app/helpers/user_helper.rb
module UserHelper
end

myvideoapp/app/helpers/videos_helper.rb
module VideosHelper
end

myvideoapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myvideoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

myvideoapp/app/views/videos/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class='container'>
      <h1>
        Videos
      </h1>
      Here are the list of videos. Click any to see analytics data.
      <ul>
      <% @videos.each do |vid| %>
      <li>
      <%= link_to vid.name,vid %>
      </li>
      <% end %>
    </ul>
    </div>
  </body>
</html>

myvideoapp/app/views/videos/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Video Usage Data</title>
  </head>
  <body>
    <div class='container'>
      <h1> Video: <%= @video.name %> </h1>
      <%= column_chart @video.usages.group(:view_time).count, xtitle: 'Viewership Percentile', ytitle:
      'Number of Users' %>
      <%= link_to 'Return to Index', videos_path %>
    </div>
  </body>

</html>